<a href="https://colab.research.google.com/github/kethyllecury/algoritimo/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


arr=(1,2,3)
array=np.array(arr)
print(array)

teste=np.zeros(5)
print(teste)


print(array.max())
print(array.min())
print(array.mean())

[1 2 3]
[0. 0. 0. 0. 0.]
3
1
2.0


In [ ]:
import numpy as np

# Exemplo com flatten
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_flatten = array_2d.flatten()
print("Array original:")
print(array_2d)
print("Array achatado (flatten):")
print(array_flatten)

# Exemplo com ravel
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
array_ravel = array_2d.ravel()
print("Array original:")
print(array_2d)
print("Array achatado (ravel):")
print(array_ravel)
array_ravel[0] = 99
print("Array original após modificação no array ravel:")
print(array_2d)

Array original:
[[1 2 3]
 [4 5 6]]
Array achatado (flatten):
[1 2 3 4 5 6]
Array original:
[[1 2 3]
 [4 5 6]]
Array achatado (ravel):
[1 2 3 4 5 6]
Array original após modificação no array ravel:
[[99  2  3]
 [ 4  5  6]]
